repos:
  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        name: ruff linting with auto-fix
      - id: ruff-format
        name: ruff code formatting

  # Local hooks using project tools
  - repo: local
    hooks:
      - id: pyright
        name: pyright type checking
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: true
        description: Run pyright type checker on changed files only

  # Conventional commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - build
          - chore
          - ci
          - docs
          - perf
          - refactor
          - revert
          - style
          - test

  # Standard pre-commit hooks for file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
      - id: end-of-file-fixer
        name: fix end of files
      - id: check-yaml
        name: check yaml syntax
      - id: check-toml
        name: check toml syntax
      - id: check-merge-conflict
        name: check for merge conflicts

  # Prettier for frontend files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: format frontend files with prettier
        args: [--no-semi, --single-quote, --trailing-comma=es5]
        files: \.(js|jsx|ts|tsx|css|scss|json|yaml|yml|md)$
        exclude: |
          (?x)^(
              package-lock\.json|
              node_modules/.*|
              \.git/.*
          )$
