[tool.isort]
profile = "black"
line_length = 88
known_first_party = [
    "tip_genius", 
    "lib" 
]
[tool.pytest.ini_options]
addopts = "-W ignore::DeprecationWarning"
pythonpath = [
  ".", "src", "tests",
]

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 88
disable = [
    "import-error",
    "no-name-in-module",
    "no-member",
    "invalid-name"
]