# Tip Genius Main Configuration File

  sports_list:
    - "Bundesliga - Germany"
    - "Premier League - England"
    - "UEFA Champions League"
  
  llm_provider_options:
    - "Mistral-Large"
    - "Google-Gemini-Flash"
    # - "Deepseek-Chat" # Sometimes has issues with JSON response
    # - "Anthropic-Claude-Haiku" # Sometimes has issues with JSON response
    # - "Anthropic-Claude-Sonnet" # Sometimes has issues with JSON response
    
  
  prediction_type_options:
    - "FourPointsScoring"
    # - "Default"
  
  named_teams_options:
    - true
    # - false
  
  additional_info_options:
    - true
    # - false