# Tip Genius Main Configuration File

  sports_list:
    - Bundesliga - Germany
    - Premier League - England
    - UEFA Champions League
  
  llm_provider_options:
    - Mistral-Large
    - Google-Gemini-Flash
    - Deepseek-Chat
    - microsoft-phi-medium
    - meta-llama-70b
    # - Anthropic-Claude-Haiku # No Json Mode: sometimes issues JSON response
    # - Anthropic-Claude-Sonnet # No Json Mode: sometimes issues JSON response

    
  
  prediction_type_options:
    - FourPointsScoring
    # - Default
  
  named_teams_options:
    - true
    # - false
  
  additional_info_options:
    - true
    # - false