# Tip Genius Main Configuration File

# List of Sports for which Tips will be generated
sports_list:
  - Premier League - England
  - Bundesliga - Germany
  - La Liga - Spain
  - UEFA Champions League

# List of LLM Providers to use for Tips generation
llm_provider_options:
  - Mistral-Medium
  - Google-Gemini-Flash
  - Deepseek-Chat
  - Meta-Llama-400b
  - Microsoft-Phi-Medium
  - OpenAI-GPT-Mini
  - OpenRouter-Grok
  # - Anthropic-Claude-Haiku # No Json Mode: sometimes has issues with JSON output

# LLM Prompt Option - Include Point Scoring System
prediction_type_options:
  - FourPointsScoring
  # - Default

# LLM Prompt Option - Include Team Names
named_teams_options:
  - true
  # - false

# LLM Prompt Option - Include Additional Information in the Prompt
additional_info_options:
  - true
  # - false

# Folder where Team Logos are stored
team_logos_folder: 'public/images/teams'
